// <auto-generated />
using System;
using LightSourceMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightSourceMonitor.Migrations;

[DbContext(typeof(MonitorDbContext))]
[Migration("20260408120000_AddWavelengthMeterSnapshots")]
partial class AddWavelengthMeterSnapshots
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

        modelBuilder.Entity("LightSourceMonitor.Models.AlarmEvent", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AlarmType")
                    .HasColumnType("INTEGER");

                b.Property<int>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<double>("Delta")
                    .HasColumnType("REAL");

                b.Property<bool>("EmailSent")
                    .HasColumnType("INTEGER");

                b.Property<int>("Level")
                    .HasColumnType("INTEGER");

                b.Property<double>("MeasuredValue")
                    .HasColumnType("REAL");

                b.Property<DateTime>("OccurredAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("ResolvedAt")
                    .HasColumnType("TEXT");

                b.Property<double>("SpecValue")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.HasIndex("ChannelId", "OccurredAt");

                b.ToTable("AlarmEvents");
            });

        modelBuilder.Entity("LightSourceMonitor.Models.MeasurementRecord", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsSyncedToTms")
                    .HasColumnType("INTEGER");

                b.Property<double>("Power")
                    .HasColumnType("REAL");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT");

                b.Property<double>("Wavelength")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.HasIndex("IsSyncedToTms");

                b.HasIndex("ChannelId", "Timestamp");

                b.ToTable("MeasurementRecords");
            });

        modelBuilder.Entity("LightSourceMonitor.Models.WavelengthMeterSnapshot", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("OneTimeValues")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("PowerValues")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("QueryDeviceId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Timestamp");

                b.HasIndex("QueryDeviceId", "Timestamp");

                b.ToTable("WavelengthMeterSnapshots");
            });

#pragma warning restore 612, 618
    }
}
