// <auto-generated />
using System;
using LightSourceMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightSourceMonitor.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    [Migration("20260327035839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("LightSourceMonitor.Models.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeasuredValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SpecValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "OccurredAt");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinAlarmLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailConfigs");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.LaserChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlarmDelta")
                        .HasColumnType("REAL");

                    b.Property<int>("ChannelIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceSN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpecPowerMax")
                        .HasColumnType("REAL");

                    b.Property<double>("SpecPowerMin")
                        .HasColumnType("REAL");

                    b.Property<double>("SpecWavelength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceSN", "ChannelIndex")
                        .IsUnique();

                    b.ToTable("LaserChannels");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.MeasurementRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncedToTms")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wavelength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsSyncedToTms");

                    b.HasIndex("ChannelId", "Timestamp");

                    b.ToTable("MeasurementRecords");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.TmsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadIntervalSec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TmsConfigs");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.AlarmEvent", b =>
                {
                    b.HasOne("LightSourceMonitor.Models.LaserChannel", "Channel")
                        .WithMany("AlarmEvents")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.MeasurementRecord", b =>
                {
                    b.HasOne("LightSourceMonitor.Models.LaserChannel", "Channel")
                        .WithMany("Measurements")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.LaserChannel", b =>
                {
                    b.Navigation("AlarmEvents");

                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
