// <auto-generated />
using System;
using LightSourceMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightSourceMonitor.Migrations
{
    [DbContext(typeof(MonitorDbContext))]
    partial class MonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("LightSourceMonitor.Models.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeasuredValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SpecValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "OccurredAt");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("LightSourceMonitor.Models.MeasurementRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncedToTms")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wavelength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsSyncedToTms");

                    b.HasIndex("ChannelId", "Timestamp");

                    b.ToTable("MeasurementRecords");
                });

#pragma warning restore 612, 618
        }
    }
}
